name: Build & Upload Lambda

on:
  push:
    paths:
      - 'lambda-build/**'
      - '.github/workflows/lambda.yml'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Lambda zip with Docker
      run: |
        cd lambda-build
        docker build -t lambda-builder .
        docker run --rm -v $PWD:/out lambda-builder cp /lambda_function.zip /out/

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-northeast-2
      run: |
        aws s3 cp lambda-build/lambda_function.zip s3://image-storage-team4-ott-project/
